
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  # a job for building the codebase
  build_and_test:    
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: go build
    - name: test
      run: go test ./... --count=1 -v