
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  # a job for building the codebase
  build_the_code:    
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: go build

  # another job to run all of our tests
  run_all_unit_tests:    
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: go test ./... --count=1 -v