# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # a job for building the codebase
  build_the_code:    
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: go build

  # another job to run all of our tests
  run_all_unit_tests:    
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: go test ./... --count=1 -v